stages:
  build:
    nodeLabel: sbt
    steps:
      - sbt universal:packageBin
    filesToStash:
      - '**'
  publish:
    nodeLabel: nvm-sbt-deployer
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm install -g npm && npm install -g serverless
        sbt "deploy Admin"
  deployDevInt:
    nodeLabel: nvm-sbt-deployer
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm install -g npm && npm install -g serverless
        sbt "deploy DevInt"
  deployUat:
    nodeLabel: nvm-sbt-deployer
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm install -g npm && npm install -g serverless
        sbt "deploy Uat"
  deployProd:
    nodeLabel: nvm-sbt-deployer
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm install -g npm && npm install -g serverless
        sbt "deploy Prod"
