addSbtPlugin("org.typelevel" % "sbt-typelevel-settings" % "0.8.3")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.8.3")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.11.5")
addSbtPlugin("com.disneystreaming.smithy4s" % "smithy4s-sbt-codegen" % "0.18.45")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.13.1")
